dist: trusty
sudo: required

services:
  - docker

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd api
      script: mvn package
      deploy:
        skip_cleanup: true
        provider: script
        script: "bash ../docker-build.sh api"
        on:
          tags: true

    - language: node_js
      node_js:
        - "9"
      before_script:
        - cd web
        - yarn install
      cache:
        directories:
          - "node_modules"
      script:
        - yarn test
        - yarn run build
      deploy:
        skip_cleanup: true
        provider: script
        script: "bash ../docker-build.sh web"
        on:
          tags: true

    - language: generic
      before_script:
        - cd db
      deploy:
        provider: script
        script: "bash ../docker-build.sh db"
        on:
          tags: true
