version: "3"

services:
  db:
    image: sam4core/consamables-db
    build: db
  api:
    image: sam4core/consamables-api
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "java", "-jar", "consamables.jar", "server", "config.yml"]
  web:
    image: sam4core/consamables-web
    build: web
    ports:
      - "80:9090"
    depends_on:
      - api

