version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: secrets/db_variables.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  api:
    image: sam4core/utensil-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "java", "-jar", "utensil.jar", "server", "config.yml"]
    env_file:
      - secrets/db_variables.env
      - secrets/api_variables.env
  web:
    image: sam4core/utensil-web
    ports:
      - "80:9090"
    depends_on:
      - api
  flyway:
    image: sam4core/docker-flyway
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:5432
    command: sh -c 'flyway -url=jdbc:postgresql://db/$${POSTGRES_USER} -user=$${POSTGRES_USER} -password=$${POSTGRES_PASSWORD} migrate'
    env_file:
      - secrets/db_variables.env

